In [1]:
#imports necess√°rios
import datetime as dt
import boto3
from pyspark.sql.types import *
from pyspark.sql.functions import *
from pyspark import SparkContext, SparkConf
from pyspark.sql import SparkSession
import matplotlib.pyplot as plt

In [2]:
format = 'json'
inferSchema = 'false'
header = 'false'
multiline = 'false'

In [3]:
#Configurando spark
conf = SparkConf().setAppName('Load').set("spark.serializer", "org.apache.spark.serializer.KryoSerializer").set("hive.exec.dynamic.partition", "true").set("hive.exec.dynamic.partition.mode", "nonstrict")
spark = SparkSession.builder.config(conf=conf).enableHiveSupport().getOrCreate()

In [4]:
#Definindo caminho dos arquivos
filePath1 = 'C:\\Users\\dbello\Documents\\pd-desafio\\Datasets - Teste Data Engineer - Passei Direto\\BASE A\\students.json'
filePath2 = 'C:\\Users\\dbello\Documents\\pd-desafio\\Datasets - Teste Data Engineer - Passei Direto\\BASE A\\courses.json'
filePath3 = 'C:\\Users\\dbello\Documents\\pd-desafio\\Datasets - Teste Data Engineer - Passei Direto\\BASE A\\subjects.json'
filePath4 = 'C:\\Users\\dbello\Documents\\pd-desafio\\Datasets - Teste Data Engineer - Passei Direto\\BASE A\\universities.json'
filePath5 = 'C:\\Users\\dbello\Documents\\pd-desafio\\Datasets - Teste Data Engineer - Passei Direto\\BASE A\\subscriptions.json'
filePath6 = 'C:\\Users\\dbello\Documents\\pd-desafio\\Datasets - Teste Data Engineer - Passei Direto\\BASE A\\sessions.json'
filePath7 = 'C:\\Users\\dbello\Documents\\pd-desafio\\Datasets - Teste Data Engineer - Passei Direto\\BASE A\\student_follow_subject.json'
filePath8 = 'C:\\Users\\dbello\Documents\\pd-desafio\\Datasets - Teste Data Engineer - Passei Direto\\BASE B\\*.json'

In [5]:
#lendo arquivo para dataframe para descobrir schema de cada json
df_students = spark.read.format(format) \
                    .option("inferSchema", inferSchema) \
                    .option("header", header) \
                    .option("multiLine", multiline) \
                    .json(filePath1)
df_courses = spark.read.format(format) \
                    .option("inferSchema", inferSchema) \
                    .option("header", header) \
                    .option("multiLine", multiline) \
                    .json(filePath2)
df_subjects = spark.read.format(format) \
                    .option("inferSchema", inferSchema) \
                    .option("header", header) \
                    .option("multiLine", multiline) \
                    .json(filePath3)
df_universities = spark.read.format(format) \
                    .option("inferSchema", inferSchema) \
                    .option("header", header) \
                    .option("multiLine", multiline) \
                    .json(filePath4)
df_subscriptions = spark.read.format(format) \
                    .option("inferSchema", inferSchema) \
                    .option("header", header) \
                    .option("multiLine", multiline) \
                    .json(filePath5)
df_sessions = spark.read.format(format) \
                    .option("inferSchema", inferSchema) \
                    .option("header", header) \
                    .option("multiLine", multiline) \
                    .json(filePath6)
df_student_follow_subject = spark.read.format(format) \
                    .option("inferSchema", inferSchema) \
                    .option("header", header) \
                    .option("multiLine", multiline) \
                    .json(filePath7)
df_baseB = spark.read.format(format) \
                    .option("inferSchema", inferSchema) \
                    .option("header", header) \
                    .option("multiLine", multiline) \
                    .json(filePath8)

In [6]:
#descobrindo o schemas de cada json
df_students.printSchema()
df_courses.printSchema()
df_subjects.printSchema()
df_universities.printSchema()
df_subscriptions.printSchema()
df_sessions.printSchema()
df_student_follow_subject.printSchema()
df_baseB.printSchema()

root
 |-- City: string (nullable = true)
 |-- CourseId: long (nullable = true)
 |-- Id: string (nullable = true)
 |-- RegisteredDate: string (nullable = true)
 |-- SignupSource: string (nullable = true)
 |-- State: string (nullable = true)
 |-- StudentClient: string (nullable = true)
 |-- UniversityId: long (nullable = true)

root
 |-- Id: long (nullable = true)
 |-- Name: string (nullable = true)

root
 |-- Id: long (nullable = true)
 |-- Name: string (nullable = true)

root
 |-- Id: long (nullable = true)
 |-- Name: string (nullable = true)

root
 |-- PaymentDate: string (nullable = true)
 |-- PlanType: string (nullable = true)
 |-- StudentId: string (nullable = true)

root
 |-- SessionStartTime: string (nullable = true)
 |-- StudentClient: string (nullable = true)
 |-- StudentId: string (nullable = true)

root
 |-- FollowDate: string (nullable = true)
 |-- StudentId: string (nullable = true)
 |-- SubjectId: long (nullable = true)

root
 |-- Last Accessed Url: string (nullable = true)
 |-- Page Category: string (nullable = true)
 |-- Page Category 1: string (nullable = true)
 |-- Page Category 2: string (nullable = true)
 |-- Page Category 3: string (nullable = true)
 |-- Page Name: string (nullable = true)
 |-- at: string (nullable = true)
 |-- browser: string (nullable = true)
 |-- carrier: string (nullable = true)
 |-- city_name: string (nullable = true)
 |-- clv_total: long (nullable = true)
 |-- country: string (nullable = true)
 |-- custom_1: string (nullable = true)
 |-- custom_2: string (nullable = true)
 |-- custom_3: string (nullable = true)
 |-- custom_4: string (nullable = true)
 |-- device_new: boolean (nullable = true)
 |-- first-accessed-page: string (nullable = true)
 |-- install_uuid: string (nullable = true)
 |-- language: string (nullable = true)
 |-- library_ver: string (nullable = true)
 |-- marketing_campaign: string (nullable = true)
 |-- marketing_medium: string (nullable = true)
 |-- marketing_source: string (nullable = true)
 |-- model: string (nullable = true)
 |-- name: string (nullable = true)
 |-- nth: long (nullable = true)
 |-- os_ver: string (nullable = true)
 |-- platform: string (nullable = true)
 |-- region: string (nullable = true)
 |-- session_uuid: string (nullable = true)
 |-- studentId_clientType: string (nullable = true)
 |-- type: string (nullable = true)
 |-- user_type: string (nullable = true)
 |-- uuid: string (nullable = true)

In [17]:
#Definindo schema
schema_students = StructType([
    StructField("City", StringType(), True),
    StructField("CourseId", LongType(),True),
    StructField("Id", StringType(), True),
    StructField("RegisteredDate", StringType(), True),
    StructField("SignupSource", StringType(), True),
    StructField("State", StringType(), True),
    StructField("StudentClient", StringType(), True),
    StructField("UniversityId", LongType(),True)])

schema_courses = StructType([
    StructField("Id", LongType(),True),
    StructField("Name", StringType(), True)])

schema_subjects = StructType([
    StructField("Id", LongType(),True),
    StructField("Name", StringType(), True)])

schema_universities = StructType([
    StructField("Id", LongType(),True),
    StructField("Name", StringType(), True)])

schema_subscriptions = StructType([
    StructField("PaymentDate",StringType(), True),
    StructField("PlanType",StringType(), True),
    StructField("StudentId", StringType(), True)])

schema_sessions = StructType([
    StructField("SessionStartTime",StringType(), True),
    StructField("StudentClient",StringType(), True),
    StructField("StudentId", StringType(), True)])

schema_student_follow_subject = StructType([
    StructField("FollowDate",StringType(), True),
    StructField("StudentId",StringType(), True),
    StructField("SubjectId", LongType(), True)])

In [18]:
#lendo arquivo para dataframe com schemas definidos
df_students = spark.read.format(format) \
                    .option("inferSchema", inferSchema) \
                    .option("header", header) \
                    .option("multiLine", multiline) \
                    .json(filePath1, schema_students).repartition(1)
df_courses = spark.read.format(format) \
                    .option("inferSchema", inferSchema) \
                    .option("header", header) \
                    .option("multiLine", multiline) \
                    .json(filePath2, schema_courses).repartition(1)
df_subjects = spark.read.format(format) \
                    .option("inferSchema", inferSchema) \
                    .option("header", header) \
                    .option("multiLine", multiline) \
                    .json(filePath3, schema_subjects).repartition(1)
df_universities = spark.read.format(format) \
                    .option("inferSchema", inferSchema) \
                    .option("header", header) \
                    .option("multiLine", multiline) \
                    .json(filePath4, schema_universities).repartition(1)
df_subscriptions = spark.read.format(format) \
                    .option("inferSchema", inferSchema) \
                    .option("header", header) \
                    .option("multiLine", multiline) \
                    .json(filePath5, schema_subscriptions).repartition(1)
df_sessions = spark.read.format(format) \
                    .option("inferSchema", inferSchema) \
                    .option("header", header) \
                    .option("multiLine", multiline) \
                    .json(filePath6, schema_sessions).repartition(1)
df_student_follow_subject = spark.read.format(format) \
                    .option("inferSchema", inferSchema) \
                    .option("header", header) \
                    .option("multiLine", multiline) \
                    .json(filePath7, schema_student_follow_subject).repartition(1)

In [19]:
df_student_follow_subject.toPandas()

,FollowDate,StudentId,SubjectId
0,2015-09-07 15:49:12.000000,0cade9bf00234e3789afc76250e4042bc1b70784ae7004...,682889
1,2015-09-07 15:49:12.000000,0cade9bf00234e3789afc76250e4042bc1b70784ae7004...,684377
2,2015-09-07 15:49:12.373000,0cade9bf00234e3789afc76250e4042bc1b70784ae7004...,698583
3,2015-09-07 15:49:12.000000,0cade9bf00234e3789afc76250e4042bc1b70784ae7004...,757882
4,2015-09-07 15:49:12.000000,0cade9bf00234e3789afc76250e4042bc1b70784ae7004...,1910475
5,2015-12-07 16:17:54.000000,8a501cab6c0a5a7e98a86f51a6264d81cdb562f4e99106...,673956
6,2015-12-07 16:17:54.000000,8a501cab6c0a5a7e98a86f51a6264d81cdb562f4e99106...,674245
7,2015-12-07 16:17:54.000000,8a501cab6c0a5a7e98a86f51a6264d81cdb562f4e99106...,681478
8,2015-12-07 16:17:54.000000,8a501cab6c0a5a7e98a86f51a6264d81cdb562f4e99106...,681925
9,2015-12-07 16:17:54.000000,8a501cab6c0a5a7e98a86f51a6264d81cdb562f4e99106...,693487
10,2016-05-30 10:31:48.000000,b8a39150d98d746853087a4107e9290976cb6c99d16a29...,670492
11,2016-05-30 10:31:48.000000,b8a39150d98d746853087a4107e9290976cb6c99d16a29...,671126
12,2016-05-30 10:31:48.000000,b8a39150d98d746853087a4107e9290976cb6c99d16a29...,686806
13,2016-05-30 10:31:48.000000,b8a39150d98d746853087a4107e9290976cb6c99d16a29...,689481
14,2016-05-30 10:31:48.000000,b8a39150d98d746853087a4107e9290976cb6c99d16a29...,1663821
15,2017-11-03 12:23:20.825720,0f6c90f966a70b84b70ea84a62d2e46ae4a2a237670815...,670937
16,2016-04-01 20:22:30.000000,0f6c90f966a70b84b70ea84a62d2e46ae4a2a237670815...,671197
17,2017-11-03 12:23:28.988978,0f6c90f966a70b84b70ea84a62d2e46ae4a2a237670815...,673846
18,2016-04-01 20:22:30.000000,0f6c90f966a70b84b70ea84a62d2e46ae4a2a237670815...,674226
19,2016-04-01 20:22:30.110000,0f6c90f966a70b84b70ea84a62d2e46ae4a2a237670815...,695790
20,2016-04-01 20:22:30.000000,0f6c90f966a70b84b70ea84a62d2e46ae4a2a237670815...,695795
21,2016-04-01 20:22:30.000000,0f6c90f966a70b84b70ea84a62d2e46ae4a2a237670815...,700140
22,2017-11-21 15:39:18.000000,388bf84cffb3219384cd7a92153cf00f3b1416e4ff1473...,669639
23,2017-11-21 15:39:18.000000,388bf84cffb3219384cd7a92153cf00f3b1416e4ff1473...,670683
24,2017-11-21 15:39:18.000000,388bf84cffb3219384cd7a92153cf00f3b1416e4ff1473...,678001
25,2017-11-21 15:39:18.000000,388bf84cffb3219384cd7a92153cf00f3b1416e4ff1473...,755622
26,2017-11-21 15:39:18.000000,388bf84cffb3219384cd7a92153cf00f3b1416e4ff1473...,1725176
27,2015-09-16 08:46:55.000000,5764c7b7c75f304749a9fa76e2cc811eb9c48535c495af...,672688
28,2015-09-16 08:46:55.000000,5764c7b7c75f304749a9fa76e2cc811eb9c48535c495af...,681089
29,2015-09-16 08:46:55.000000,5764c7b7c75f304749a9fa76e2cc811eb9c48535c495af...,681472
...,...,...,...
317257,2017-11-30 21:43:14.000000,509d16d5a15d47ff8290b70c2957368d5dd79489f6a339...,669867
317258,2017-11-30 21:43:14.000000,509d16d5a15d47ff8290b70c2957368d5dd79489f6a339...,670384
317259,2017-11-30 21:43:14.000000,509d16d5a15d47ff8290b70c2957368d5dd79489f6a339...,672578
317260,2017-11-30 21:43:14.000000,509d16d5a15d47ff8290b70c2957368d5dd79489f6a339...,796310
317261,2017-11-30 21:49:38.000000,0cde7b5c3228dec794d2dfd3443d12af2e3d931010d053...,1745737
317262,2017-11-30 21:49:38.000000,0cde7b5c3228dec794d2dfd3443d12af2e3d931010d053...,3465744
317263,2017-11-30 21:49:38.000000,0cde7b5c3228dec794d2dfd3443d12af2e3d931010d053...,6503734
317264,2017-11-30 21:49:38.000000,0cde7b5c3228dec794d2dfd3443d12af2e3d931010d053...,10952644
317265,2017-11-30 21:49:38.000000,0cde7b5c3228dec794d2dfd3443d12af2e3d931010d053...,24798029
317266,2017-11-30 21:51:03.000000,3aa9716eea237dd9f225b5e4b1c406438283d0ce327e36...,792825
317267,2017-11-30 21:51:03.000000,3aa9716eea237dd9f225b5e4b1c406438283d0ce327e36...,1749970
317268,2017-11-30 21:51:03.000000,3aa9716eea237dd9f225b5e4b1c406438283d0ce327e36...,3713406
317269,2017-11-30 21:51:03.000000,3aa9716eea237dd9f225b5e4b1c406438283d0ce327e36...,3713416
317270,2017-11-30 21:51:03.000000,3aa9716eea237dd9f225b5e4b1c406438283d0ce327e36...,4306546
317271,2017-11-30 21:49:41.000000,1997cd55824cddb29f38de0da36dd9810e85670491eb90...,703359
317272,2017-11-30 21:49:41.000000,1997cd55824cddb29f38de0da36dd9810e85670491eb90...,1593900
317273,2017-11-30 21:49:41.000000,1997cd55824cddb29f38de0da36dd9810e85670491eb90...,24509075
317274,2017-11-30 21:49:41.000000,1997cd55824cddb29f38de0da36dd9810e85670491eb90...,28006228
317275,2017-12-01 17:34:38.643798,1997cd55824cddb29f38de0da36dd9810e85670491eb90...,30954805
317276,2017-11-30 21:49:41.000000,1997cd55824cddb29f38de0da36dd9810e85670491eb90...,35897721
317277,2017-11-30 21:51:20.000000,5ef0abe88edad2f786f0b06f7b3d927100306d25c8d018...,671126
317278,2017-11-30 21:51:20.000000,5ef0abe88edad2f786f0b06f7b3d927100306d25c8d018...,686268
317279,2017-11-30 21:51:20.000000,5ef0abe88edad2f786f0b06f7b3d927100306d25c8d018...,691379
317280,2017-11-30 21:51:20.000000,5ef0abe88edad2f786f0b06f7b3d927100306d25c8d018...,3208294
317281,2017-11-30 21:51:20.000000,5ef0abe88edad2f786f0b06f7b3d927100306d25c8d018...,5947347
317282,2017-11-30 21:51:33.000000,8693cb6009fb627a21c564191c35729af006f8358c6eb8...,670780
317283,2017-11-30 21:51:33.000000,8693cb6009fb627a21c564191c35729af006f8358c6eb8...,671086
317284,2017-11-30 21:51:33.000000,8693cb6009fb627a21c564191c35729af006f8358c6eb8...,671154
317285,2017-11-30 21:51:33.000000,8693cb6009fb627a21c564191c35729af006f8358c6eb8...,671601
317286,2017-11-30 21:51:33.000000,8693cb6009fb627a21c564191c35729af006f8358c6eb8...,671714

In [20]:
df_students.write.parquet('C:\\Users\\dbello\Documents\\pd-desafio\\raw_data\\students')

In [21]:
df_courses.write.parquet('C:\\Users\\dbello\Documents\\pd-desafio\\raw_data\\courses')

In [22]:
df_subjects.write.parquet('C:\\Users\\dbello\Documents\\pd-desafio\\raw_data\\subjects')

In [23]:
df_universities.write.parquet('C:\\Users\\dbello\Documents\\pd-desafio\\raw_data\\universities')

In [27]:
df_subscriptions.write.parquet('C:\\Users\\dbello\Documents\\pd-desafio\\raw_data\\subscriptions')

In [25]:
df_sessions.write.parquet('C:\\Users\\dbello\Documents\\pd-desafio\\raw_data\\sessions')

In [26]:
df_student_follow_subject.write.parquet('C:\\Users\\dbello\Documents\\pd-desafio\\raw_data\\student_follow_subject')